#!/usr/bin/env bash

Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White


DECK_STARTUP_FILE="/home/deck/.steam/steam/steamui/overrides/movies/deck_startup.webm"
DECK_STARTUP_FILE_SIZE=1840847

DECK_SUSPEND_FILE="/home/deck/.steam/steam/steamui/overrides/movies/deck-suspend-animation.webm"
DECK_SUSPEND_FILE_SIZE=160008
