#!/usr/bin/env bash

Color_Off='\033[0m'       # Text Reset

# Regular Colors
Black='\033[0;30m'        # Black
Red='\033[0;31m'          # Red
Green='\033[0;32m'        # Green
Yellow='\033[0;33m'       # Yellow
Blue='\033[0;34m'         # Blue
Purple='\033[0;35m'       # Purple
Cyan='\033[0;36m'         # Cyan
White='\033[0;37m'        # White


DECK_STARTUP_FILE="$HOME/.steam/root/config/uioverrides/movies/deck_startup.webm"

DECK_SUSPEND_FILE="$HOME/.steam/root/config/uioverrides/movies/deck-suspend-animation.webm"
DECK_SUSPEND_FILE_THROBBER="$HOME/.steam/root/config/uioverrides/movies/deck-suspend-animation-from-throbber.webm"

DECK_JS_FILE="$HOME/.steam/steam/steamui/library.js"
